-- ==========================================
-- ChartMon Supabase SQL Database Schema Setup
-- ==========================================

-- 1. Quizzes Table (퀴즈 데이터베이스)
-- ------------------------------------------
create table if not exists public.quizzes (
    id bigint generated by default as identity primary key,
    category text not null,
    theory_ref text not null,
    question text not null,
    chart_data jsonb not null,        -- Candlestick coordinates (시/고/저/종)
    drawings jsonb default '[]'::jsonb, -- Indicator drawings overlay
    options text[] not null,          -- 객관식 보기 4개
    correct_index integer not null,
    explanation text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) for quizzes
alter table public.quizzes enable row level security;

-- Read policy: Anyone can read quizzes (모든 유저 읽기 가능)
create policy "Enable read access for all users" on public.quizzes 
    for select using (true);


-- 2. Profiles Table (유저 수준 및 게임 정보 테이블)
-- ------------------------------------------
create table if not exists public.profiles (
    id uuid references auth.users on delete cascade primary key,
    streak integer default 5 not null,
    xp integer default 150 not null,
    trading_level integer default 1 not null, -- 1단계 ~ 5단계
    completed_quizzes bigint[] default '{}'::bigint[] not null,
    last_active_date text,                    -- 마지막 활성/학습 날짜 (YYYY-MM-DD)
    last_daily_completed_date text,           -- 마지막 데일리 트레이닝 완료 날짜 (YYYY-MM-DD)
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

-- CRUD policies for profiles
create policy "Allow users to read their own profile" on public.profiles
    for select using (auth.uid() = id);

create policy "Allow users to update their own profile" on public.profiles
    for update using (auth.uid() = id);


-- 3. Automatic Profile Creation Trigger
-- ------------------------------------------
-- 신규 유저 회원가입 시 auth.users에 행이 삽입되면 public.profiles에 자동으로 기본 프로필 행을 생성해주는 트리거
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, streak, xp, trading_level, completed_quizzes)
  values (
    new.id, 
    5,   -- 기본 스트릭 5일 부여
    150, -- 기본 150 XP 부여 (1단계 Paper Trader로 시작)
    1,   -- 1단계 레벨
    '{}'::bigint[]
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger binding
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
